
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HotelApp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class hardware_table
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public hardware_table()
    {

        this.room_hardware = new HashSet<room_hardware>();

    }


    public int hardware_id { get; set; }

    public string hardware_name { get; set; }

    public string hardware_count { get; set; }

    public string number_room { get; set; }



    public virtual hotelrooms hotelrooms { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<room_hardware> room_hardware { get; set; }

}

}
