//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal_table
    {
        public int id_journal_table { get; set; }
        public string login_users { get; set; }
        public Nullable<System.DateTime> journal_datetime { get; set; }
        public int id_do_table { get; set; }
    
        public virtual do_table do_table { get; set; }
        public virtual users users { get; set; }
    }
}
