
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HotelApp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class listresidents
{

    public string passport { get; set; }

    public string number_room { get; set; }

    public System.DateTime settlement_date { get; set; }

    public System.DateTime eviction_date { get; set; }

    public int id_listres { get; set; }



    public virtual hotelrooms hotelrooms { get; set; }

    public virtual residents residents { get; set; }

}

}
