
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HotelApp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class residents
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public residents()
    {

        this.listresidents = new HashSet<listresidents>();

    }


    public string passport { get; set; }

    public string last_name { get; set; }

    public string first_name { get; set; }

    public string patronymic { get; set; }

    public System.DateTime birth { get; set; }

    public int gend_id { get; set; }

    public string address { get; set; }

    public string number_phone { get; set; }

    public string scanpass { get; set; }

    public string destination { get; set; }

    public string info { get; set; }



    public virtual gender_table gender_table { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<listresidents> listresidents { get; set; }

}

}
