
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HotelApp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class room_hardware
{

    public Nullable<int> hardware_id { get; set; }

    public string number_room { get; set; }

    public int id { get; set; }



    public virtual hardware_table hardware_table { get; set; }

    public virtual hotelrooms hotelrooms { get; set; }

}

}
